type Movie {
    id: ID
    title: String
    year: Int
    trailer: String
    rated: String
    released: String
    runtime: String
    genre: [String]
    director: String
    writer: String
    actors: String
    plot: String
    languages: String
    country: String
    awards: String
    poster: String
    nfFileId: Int
    metaScore: Int
    imdbRating: String
    imdbVotes: Int
    type: String
    response: Boolean
    images: [MovieImage]
    categories: String
}

type MovieImage {
    id: ID
    fileId: ID
    name: String
    format: String
    type: Int
    url: String
}

type MoviePage {
    page: Int!
    pageSize: Int!
    total: Int!
    totalPages: Int!
    items: [Movie!]
}

type MovieByCategory {
    category: String
    movies: [Movie]
}

type MovieByGenre {
    genre: String
    movies: [Movie]
}

# Request
input MovieByGenreRequest {
    limit: Int
    genres: [String]
}

input MovieFilterRequest {
    genres: [String]
    countries: [String]
    languages: [String]
    year: String
    rating: String
    rated: String
    type: String
    title: String
    sort: String
    page: Int
    pageSize: Int
}

input MovieInput {
    id: ID
    title: String
    year: Int
    trailer: String
    rated: String
    released: String
    runtime: String
    genre: [String]
    director: String
    writer: String
    actors: String
    plot: String
    languages: String
    country: String
    awards: String
    nfFileId: Int
    metaScore: Int
    imdbRating: String
    imdbVotes: Int
    type: String
    response: Boolean
    categories: String
    images: [MovieImageInput]
}

input MovieImageInput {
    id: ID
    fileId: ID
    name: String
    format: String
    type: Int
    url: String
}

type Query {
    getAllMovie(page: Int = 0, pageSize: Int = 10, filter: String = "", sort: String = ""): MoviePage
    getMovieByCategory: [MovieByCategory]
    getMovieById(id: ID!): Movie
    getMoviesByGenres(request: MovieByGenreRequest!): [MovieByGenre]
    getMoviesByFilter(request: MovieFilterRequest!): MoviePage
}

type Mutation {
    createMovie(movie: MovieInput!): Movie
    createListMovie(movies: [MovieInput!]!): [Movie]!
    updateMovie(id: ID!, movie: MovieInput!): Boolean
    deleteMovie(id: ID!): Boolean
}