# Profile
type Profile {
    id: ID!
    name: String!
    avatar: String
    status: StatusEnum!
    type: TypeEnum!
    password: String
    description: String
}

enum StatusEnum {
    ACTIVE
    INACTIVE
    LOCKED
}

enum TypeEnum {
    DEFAULT
    KIDS
    ADULT
}

# Input
input ProfileInput {
    name: String!
    avatar: String
    status: StatusEnum!
    type: TypeEnum!
    password: String
    description: String
}

extend type Query {
    getAllProfile: [Profile]
    getProfileById(id: ID!): [Profile]
    getAllProfileByUserId(id: ID!): [Profile]
}

extend type Mutation {
    createProfile(profile: ProfileInput!): Profile
    updateProfile(id: ID!, profile: ProfileInput!): Boolean
    deleteProfile(id: ID!): Boolean
}