spring.application.name=netfliz
server.port = 8080

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/netfliz
spring.datasource.username=root
spring.datasource.password=280301
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#Overriding bean definition
spring.main.allow-bean-definition-overriding=true

#mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pts.28032001@gmail.com
spring.mail.password=rnivbrvjwtgjdqia
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#JWT configuration
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

#Mongo config
spring.data.mongodb.auto-index-creation=true

# Specify the Lucene Directory (in RAM for POC)
spring.jpa.properties.hibernate.search.default.directory_provider = local-heap


# firebase storage base url
firebase.storage.base-url=https://firebasestorage.googleapis.com/v0/b/netfliz-19a9c.appspot.com/o/

spring.graphql.cors.allowed-origins=*
spring.graphql.cors.allowed-methods=GET,POST, PUT, DELETE, OPTIONS
spring.graphql.cors.max-age=1800s

#file upload configuration
# Set the maximum file size to 5MB
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
