spring.application.name=netfliz
server.port=${SERVER_PORT:8080}
# Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
#mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pts.28032001@gmail.com
spring.mail.password=rnivbrvjwtgjdqia
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#JWT configuration
application.security.jwt.secret-key=${APPLICATION_SECURITY_JWT_SECRET_KEY}
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000
# firebase storage base url
firebase.storage.base-url=${FIREBASE_STORAGE_BASE_URL}
firebase.storage.config-path=${FIREBASE_STORAGE_CONFIG_PATH}
firebase.storage.config-base64=${FIREBASE_STORAGE_CONFIG_BASE64}
firebase.storage.bucket-name=${FIREBASE_STORAGE_BUCKET_NAME}
spring.cors.allowed-origin-patterns=${SPRING_CORS_ALLOWED_ORIGIN_PATTERNS}
spring.graphql.cors.allowed-origins=*
spring.graphql.cors.allowed-methods=GET,POST, PUT, DELETE, OPTIONS
spring.graphql.cors.max-age=1800s
spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}
spring.data.redis.username=${SPRING_DATA_REDIS_USERNAME}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD}
# aws s3 configuration
backblaze.s3.endpoint=${BACKBLAZE_S3_ENDPOINT}
backblaze.s3.region=${BACKBLAZE_S3_REGION}
backblaze.s3.access-key-id=${BACKBLAZE_S3_ACCESS_KEY_ID}
backblaze.s3.secret-access-key=${BACKBLAZE_S3_SECRET_ACCESS_KEY}
backblaze.s3.bucket-name=${BACKBLAZE_S3_BUCKET_NAME}
backblaze.s3.worker-shared-secret=${BACKBLAZE_S3_WORKER_SHARED_SECRET}
# proxy cnd
proxy.cdn.url=${PROXY_CDN_URL}