# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/netfliz
spring.datasource.username=netfliz
spring.datasource.password=280301
# security
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
spring.cors.allowed-origin-patterns=http://localhost:*,https://*.up.railway.app
# firebase storage base url
firebase.storage.base-url=${FIREBASE_STORAGE_BASE_URL:https://firebasestorage.googleapis.com/v0/b/abc-19a9c.appspot.com/o/}
firebase.storage.config-path=${FIREBASE_STORAGE_CONFIG_PATH:/data/firebase-service-account.json}
firebase.storage.config-base64=${FIREBASE_STORAGE_CONFIG_BASE64:abc}
firebase.storage.bucket-name=${FIREBASE_STORAGE_BUCKET_NAME:bucket}
# redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.username=netfliz
spring.data.redis.password=280301
# aws s3 configuration
backblaze.s3.endpoint=${BACKBLAZE_S3_ENDPOINT:https://s3.us-west-004.backblazeb2.com}
backblaze.s3.region=${BACKBLAZE_S3_REGION:us-west-004}
backblaze.s3.access-key-id=${BACKBLAZE_S3_ACCESS_KEY_ID:abc}
backblaze.s3.secret-access-key=${BACKBLAZE_S3_SECRET_ACCESS_KEY:abc}
backblaze.s3.bucket-name=${BACKBLAZE_S3_BUCKET_NAME:bucket}
backblaze.s3.worker-shared-secret=${BACKBLAZE_S3_WORKER_SHARED_SECRET:abc}
# proxy cnd
proxy.cdn.url=${PROXY_CDN_URL}