spring.application.name=netfliz
server.port=8080

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/netfliz
spring.datasource.username=root
spring.datasource.password=280301

#mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pts.28032001@gmail.com
spring.mail.password=rnivbrvjwtgjdqia
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#JWT configuration
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

# firebase storage base url
firebase.storage.base-url=${FIREBASE_STORAGE_BASE_URL}
firebase.config.path=${FIREBASE_CONFIG_PATH}
firebase.config.base64=${FIREBASE_CONFIG_BASE64}

spring.cors.allowed-origin-patterns=http://localhost:*,https://*.up.railway.app

spring.graphql.cors.allowed-origins=*
spring.graphql.cors.allowed-methods=GET,POST, PUT, DELETE, OPTIONS
spring.graphql.cors.max-age=1800s
